#!/bin/sh

# opsiconfd is part of the device management solution opsi http://www.opsi.org
# Copyright (c) 2008-2025 uib GmbH <info@uib.de>
# All rights reserved.
# License: AGPL-3.0-only

# The opsi monitoring module is required for this function: https://opsi.org/de/extensions

# Run "opsiconfd health-check --list" to view available checks.
# Use "opsiconfd health-check --documentation" for detailed information about each check.
# To disable specific checks, add skip-checks=[<check1>, <check2>] in /etc/opsi/opsiconfd.conf.
# To run only selected checks, add checks=[<check1>, <check2>] in /etc/opsi/opsiconfd.conf.

# Further details are available at https://docs.opsi.org/opsi-docs-en/stable/server/components/monitoring.html

/usr/bin/opsiconfd health-check --format checkmk
exit 0
