#!/bin/sh

# opsiconfd is part of the device management solution opsi http://www.opsi.org
# Copyright (c) 2008-2025 uib GmbH <info@uib.de>
# All rights reserved.
# License: AGPL-3.0-only

# The opsi monitoring module is required for this function: https://opsi.org/de/extensions

# Run "opsiconfd health-check --list" to view available checks.
# Use "opsiconfd health-check --documentation" for detailed information about each check.
# Call this script with a specific check ID as an argument to get the result in Zabbix format.

# Further details are available at https://docs.opsi.org/opsi-docs-en/stable/server/components/monitoring.html

/usr/bin/opsiconfd health-check --format zabbix --checks=$1
