FROM docker.uib.gmbh/opsi/dev/pybuilder:uib-python-3.11 as opsiconfd_development_build_43

ARG DOCKER_ENV
ARG USER
ARG UID

ENV DOCKER_ENV=${DOCKER_ENV} \
	DEV_USER=${USER} \
	DEV_UID=${UID} \
	OPSI_REPO=https://download.opensuse.org/repositories/home:/uibmz:/opsi:/4.3:/development/Debian_9.0/ \
	# python:
	PYTHONFAULTHANDLER=1 \
	PYTHONUNBUFFERED=1 \
	PYTHONHASHSEED=random \
	# pip:
	PIP_NO_CACHE_DIR=off \
	PIP_DISABLE_PIP_VERSION_CHECK=on \
	PIP_DEFAULT_TIMEOUT=100

# System deps:
RUN apt-get update \
	&& apt-get --yes dist-upgrade \
	&& apt-get --yes install \
		cpio \
		vim \
		wget \
		gettext \
		mariadb-client \
		libmariadb-dev \
		psmisc \
		librsync1 \
		sqlite3 \
		sudo \
		git \
		bash-completion \
		nano \
		netcat \
		supervisor \
	&& mkdir -p /usr/local/share/keyrings \
	&& wget -q -O - https://packages.grafana.com/gpg.key | gpg --dearmor > /usr/local/share/keyrings/grafana.gpg \
	&& echo "deb [signed-by=/usr/local/share/keyrings/grafana.gpg] https://packages.grafana.com/oss/deb stable main" > /etc/apt/sources.list.d/grafana.list \
	&& wget -q -O - ${OPSI_REPO}Release.key | gpg --dearmor > /usr/local/share/keyrings/opsi.gpg \
	&& echo "deb [signed-by=/usr/local/share/keyrings/opsi.gpg] ${OPSI_REPO} /" > /etc/apt/sources.list.d/opsi.list \
	&& apt-get update \
	&& apt-get --yes install \
		apt-transport-https \
		software-properties-common \
		grafana \
		mariadb-server \
		redis-tools \
		redis-server \
		redis-timeseries \
		opsi-utils \
	&& apt-get clean

COPY docker/files/ /

# Setup poetry
WORKDIR /workspace

RUN useradd --create-home -s /bin/bash ${DEV_USER} \
	&& (getent group opsifileadmins || groupadd opsifileadmins) \
	&& (getent group opsiadmin || groupadd opsiadmin) \
	&& (getent passwd opsiconfd || useradd --system -g opsifileadmins -d /var/lib/opsi -s /bin/bash opsiconfd) \
	&& (getent passwd adminuser || useradd --create-home --home-dir /home/adminuser -s /bin/bash adminuser) \
	&& echo "adminuser:adminuser" | chpasswd \
	&& adduser adminuser opsifileadmins \
	&& adduser adminuser opsiadmin \
	&& echo "${DEV_USER}:adminuser" | chpasswd \
	&& adduser ${DEV_USER} opsifileadmins \
	&& adduser ${DEV_USER} opsiadmin \
	&& adduser ${DEV_USER} sudo \
	&& adduser ${DEV_USER} shadow \
	&& chown -R ${DEV_USER}:${DEV_USER} /home/${DEV_USER}/ \
	&& echo "${DEV_USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \
	&& cp -r /root/.bash* /home/adminuser/ \
	&& cp -r /root/.bash* /home/${DEV_USER}/ \
	&& chmod g+rw -R . \
	&& chmod +x /*entrypoint.sh \
	&& mkdir tftpboot \
	&& chown -R $DEV_USER /workspace
