base_dir=$(dirname $(readlink -f $0))/..
common_env_file=${base_dir}/docker/opsiconfd-dev/common.env
env_file=${base_dir}/docker/opsiconfd-dev/.env

echo "Install git-hooks"
opsi-dev-cli git-hook install

echo "Writing env file: ${env_file}"

if [ -e $env_file ]; then
	set -o allexport
	. $env_file
	set +o allexport
fi

[ -z "$OPSISERVER_DEV_OPSICONFD_FORWARD_PORT" ] && OPSISERVER_DEV_OPSICONFD_FORWARD_PORT="44431:"
[ -z "$OPSISERVER_CS_OPSICONFD_FORWARD_PORT" ] && OPSISERVER_CS_OPSICONFD_FORWARD_PORT="44432:"
if [ -z "${LOCAL_WORKSPACE_DIR}" ] || [ ! -e "${LOCAL_WORKSPACE_DIR}/pyproject.toml" ]; then
	LOCAL_WORKSPACE_DIR="${base_dir}"
fi
[ -z "${OPSILICSRV_URL}" ] && echo "Please set OPSILICSRV_URL in $env_file" >&2
[ -z "${OPSILICSRV_TOKEN}" ] && echo "Please set OPSILICSRV_TOKEN in $env_file" >&2

cat <<EOF > $env_file
# Generated by .devcontainer/initialize.sh

# Content from $common_env_file
EOF
cat $common_env_file >> $env_file


cat <<EOF >> $env_file

# Dynamically added content
OPSISERVER_DEV_OPSICONFD_FORWARD_PORT=${OPSISERVER_DEV_OPSICONFD_FORWARD_PORT}
OPSISERVER_CS_OPSICONFD_FORWARD_PORT=${OPSISERVER_CS_OPSICONFD_FORWARD_PORT}
LOCAL_WORKSPACE_DIR="${LOCAL_WORKSPACE_DIR}"
USER="$(id -u -n)"
DEV_USER="$(id -u -n)"
DEV_UID=$(id -u)
OPSILICSRV_URL="${OPSILICSRV_URL}"
OPSILICSRV_TOKEN="${OPSILICSRV_TOKEN}"
EOF
