base_dir=$(dirname $(readlink -f $0))/..
common_env_file=${base_dir}/docker/opsiconfd-dev/common.env
env_file=${base_dir}/docker/opsiconfd-dev/.env

echo "Install git-hooks"
opsi-dev-tool git-hooks --install

echo "Writing env file: ${env_file}"

if [ -e $env_file ]; then
	set -o allexport
	source $env_file
	set +o allexport
fi

[ -z "$OPSISERVER_DEV_OPSICONFD_FORWARD_PORT" ] && OPSISERVER_DEV_OPSICONFD_FORWARD_PORT="44431:"
[ -z "$OPSISERVER_CS_OPSICONFD_FORWARD_PORT" ] && OPSISERVER_CS_OPSICONFD_FORWARD_PORT="44432:"

cat <<EOF > $env_file
# Generated by .devcontainer/initialize.sh

# Content from $common_env_file
EOF
cat $common_env_file >> $env_file


cat <<EOF >> $env_file

# Dynamically added content
OPSISERVER_DEV_OPSICONFD_FORWARD_PORT=${OPSISERVER_DEV_OPSICONFD_FORWARD_PORT}
OPSISERVER_CS_OPSICONFD_FORWARD_PORT=${OPSISERVER_CS_OPSICONFD_FORWARD_PORT}
OPSILICSRV_URL=${OPSILICSRV_URL}
OPSILICSRV_TOKEN=${OPSILICSRV_TOKEN}
LOCAL_WORKSPACE_DIR=../..
DEV_USER=${USER}
DEV_UID=$(id -u $USER)
EOF
