#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys,os

# if started manualy from the dev dir, append pwd to path
if os.path.dirname(os.path.abspath(sys.argv[0])) == os.path.abspath('scripts'):
	sys.path.insert(0, './')



from opsiconfd.opsiconfd import main

if __name__=="__main__":
	sys.exit(main())
