version: '3.8'

volumes:
  mysql-dev_data44:
    driver: local
  redis-dev_data44:
    driver: local
  grafana-dev_data44:
    driver: local
  mysql-cs_data44:
    driver: local
  redis-cs_data44:
    driver: local
  grafana-cs_data44:
    driver: local

services:
  opsiserver44-dev:
    hostname: opsiserver44-dev
    domainname: opsi.test
    # Needed for mount
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
      - SYS_PTRACE
    depends_on:
      - mysql-dev44
      - redis-dev44
      - grafana-dev44
    build:
      context: .
      args:
        DEV_USER: $DEV_USER
        DEV_UID: $DEV_UID
    volumes:
      - ${LOCAL_WORKSPACE_DIR}:/workspace:cached,rslave
    ports:
      - ${OPSISERVER_DEV_OPSICONFD_FORWARD_PORT}4447
    env_file:
      - .env
      - opsiserver44-dev.env

  mysql-dev44:
    image: mariadb:10.7
    restart: ${RESTART_POLICY}
    hostname: mysql-dev44
    command: --max_connections=${MYSQL_MAX_CONNECTIONS} --max_allowed_packet=${MYSQL_MAX_ALLOWED_PACKET} --sort_buffer_size=${MYSQL_SORT_BUFFER_SIZE}
    env_file:
      - .env
    volumes:
      - mysql-dev_data44:/var/lib/mysql

  redis-dev44:
    image: redislabs/redistimeseries:latest
    restart: ${RESTART_POLICY}
    hostname: redis-dev44
    #command: sh -c "redis-server --requirepass $$REDIS_PASSWORD --loadmodule /usr/lib/redis/modules/redistimeseries.so"
    command: sh -c "redis-server --loadmodule /usr/lib/redis/modules/redistimeseries.so"
    env_file:
      - .env
    volumes:
      - redis-dev_data44:/data

  grafana-dev44:
    image: grafana/grafana:latest
    restart: ${RESTART_POLICY}
    hostname: grafana-dev
    env_file:
      - .env
    volumes:
      - grafana-dev_data44:/var/lib/grafana

  opsiserver44-cs:
    hostname: opsiserver44-cs
    domainname: opsi.test
    # Needed for mount
    privileged: true
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
      - SYS_PTRACE
    depends_on:
      - mysql-cs44
      - redis-cs44
      - grafana-cs44
    build:
      context: .
      args:
        DEV_USER: $DEV_USER
        DEV_UID: $DEV_UID
    volumes:
      - ${LOCAL_WORKSPACE_DIR}:/workspace:cached
    ports:
      - ${OPSISERVER_CS_OPSICONFD_FORWARD_PORT}4447
    env_file:
      - .env
      - opsiserver44-cs.env
    command: poetry run opsiconfd

  mysql-cs44:
    image: mariadb:10.7
    restart: ${RESTART_POLICY}
    hostname: mysql-cs44
    command: --max_connections=${MYSQL_MAX_CONNECTIONS} --max_allowed_packet=${MYSQL_MAX_ALLOWED_PACKET} --sort_buffer_size=${MYSQL_SORT_BUFFER_SIZE}
    env_file:
      - .env
    volumes:
      - mysql-cs_data44:/var/lib/mysql

  redis-cs44:
    image: redislabs/redistimeseries:latest
    restart: ${RESTART_POLICY}
    hostname: redis-configserver44
    #command: sh -c "redis-server --requirepass $$REDIS_PASSWORD --loadmodule /usr/lib/redis/modules/redistimeseries.so"
    command: sh -c "redis-server --loadmodule /usr/lib/redis/modules/redistimeseries.so"
    env_file:
      - .env
    volumes:
      - redis-cs_data44:/data

  grafana-cs44:
    image: grafana/grafana:latest
    restart: ${RESTART_POLICY}
    hostname: grafana-cs44
    env_file:
      - .env
    volumes:
      - grafana-cs_data44:/var/lib/grafana
